###
GET http://localhost:3001/users


//--------------------------------------------------------------------------------




#EXAMPLES

###
POST http://localhost:3001/register
Content-Type: application/json

{
    "email": "emre@gmail.com",
    "password": "1"
}



###
POST http://localhost:3001/login
Content-Type: application/json

{
    "email": "emre@gmail.com",
    "password": "1"
}