###
GET http://localhost:3001/users


//--------------------------------------------------------------------------------


### 
POST https://localhost:3001/login
Content-Type: application/json
{
    "password": "1",
    "email": "1@gmail.com"
}

#EXAMPLES

###
POST http://localhost:3001/register
Content-Type: application/json

{
    "email": "132@gmail.com",
    "password": "1"
}



###
POST http://localhost:3001/login
Content-Type: application/json

{
    "email": "132@gmail.com",
    "password": "1"
}